version: "3"
services:
  jupyter:
    build:
      context: ./docker/jupyter
    image: ${JUPYTER_IMAGE_NAME}:${VERSION}
    container_name: jupyter
    ports:
      - "${JUPYTER_PORT}:8888"
      - "${BENTOML_SERVE_PORT}:3000"
    environment:
      BENTOML_HOME: ${BENTOML_HOME}
    volumes:
      - ./:/opt/project
    stdin_open: true
    tty: true
    command: >
      bash -c "
      cd / && jupyter notebook --no-browser --allow-root --ip='*' --port=8888 --NotebookApp.password='' --NotebookApp.token=''
      "

  postgres:
    build:
      context: ./docker/postgres
    image: ${POSTGRES_IMAGE_NAME}:${VERSION}
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  zookeeper:
    image: quay.io/debezium/zookeeper:latest
    container_name: zookeper-car-data

  kafka:
    image: quay.io/debezium/kafka:latest
    container_name: kafka
    ports:
     - "${KAFKA_PORT}:9092"
    links:
     - zookeeper
    environment:
      ZOOKEEPER_CONNECT: ${ZOOKEEPER_CONNECT}

  adminer:
    image: adminer
    ports:
      - 8080:8080

  connect:
    build:
      context: ./docker/debezium
      args:
        DEBEZIUM_VERSION: latest
    image: ${DEBEZIUM_IMAGE_NAME}:${VERSION}
    container_name: debezium
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka:kafka
     - postgres:postgres
    environment:
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      GROUP_ID: ${GROUP_ID}
      CONFIG_STORAGE_TOPIC: ${CONFIG_STORAGE_TOPIC}
      OFFSET_STORAGE_TOPIC: ${OFFSET_STORAGE_TOPIC}
      STATUS_STORAGE_TOPIC: ${STATUS_STORAGE_TOPIC}
      CONNECT_JDBC_URL: ${CONNECT_JDBC_URL}
