CREATE TABLE IF NOT EXISTS TBL_CAR_PRICE (
    ID SERIAL PRIMARY KEY,
    MODEL VARCHAR(50), 
    YEAR INTEGER,
    PRICE INTEGER,
    TRANSMISSION VARCHAR(50),
    MILEAGE INTEGER,
    FUEL_TYPE VARCHAR(50),
    TAX INTEGER,
    MPG FLOAT,
    ENGINE_SIZE FLOAT,

    -- additional field
    SUGGESTED_PRICE INTEGER
);
